//
// EPITECH PROJECT, 2018
// cpp_indie_studio - IrrKeyToStr.cpp
// File description:
// Created by Gregory EPLE
//

#include "IrrKeyToStr.hpp"

bomb::IrrKeyToStr::IrrKeyToStr() :
	_keys({ {irr::KEY_LBUTTON, L"MOUSE LEFT"},
		{irr::KEY_RBUTTON, L"MOUSE RIGHT"},
		{irr::KEY_CANCEL , L"CANCEL"},
		{irr::KEY_MBUTTON, L"MOUSE MIDDLE"},
		{irr::KEY_XBUTTON1, L"MOUSE 1"},
		{irr::KEY_XBUTTON1, L"MOUSE 2"},
		{irr::KEY_BACK, L"BACKSPACE"},
		{irr::KEY_TAB, L"TAB"},
		{irr::KEY_CLEAR, L"CLEAR"},
		{irr::KEY_RETURN, L"ENTER"},
		{irr::KEY_SHIFT, L"SHIFT"},
		{irr::KEY_CONTROL, L"CTRL"},
		{irr::KEY_MENU, L"ALT"},
		{irr::KEY_PAUSE, L"PAUSE"},
		{irr::KEY_CAPITAL, L"CAPS LOCK"},
		{irr::KEY_KANA, L"KANA"},
		{irr::KEY_HANGUEL, L"HANGUEL"},
		{irr::KEY_HANGUL, L"HANGUL"},
		{irr::KEY_JUNJA, L"JUNJA"},
		{irr::KEY_FINAL, L"FINAL"},
		{irr::KEY_HANJA, L"HANJA"},
		{irr::KEY_KANJI, L"KANJI"},
		{irr::KEY_ESCAPE , L"ESCAPE"},
		{irr::KEY_CONVERT, L"CONVERT"},
		{irr::KEY_NONCONVERT, L"NONCONVERT"},
		{irr::KEY_ACCEPT, L"ACCEPT"},
		{irr::KEY_MODECHANGE, L"MODE CHANGE"},
		{irr::KEY_SPACE, L"SPACE"},
		{irr::KEY_PRIOR, L"PAGE UP"},
		{irr::KEY_NEXT, L"PAGE Down"},
		{irr::KEY_END, L"END"},
		{irr::KEY_HOME, L"HOME"},
		{irr::KEY_LEFT, L"LEFT"},
		{irr::KEY_UP, L"UP"},
		{irr::KEY_RIGHT, L"RIGHT"},
		{irr::KEY_DOWN, L"DOWN"},
		{irr::KEY_SELECT, L"SELECT"},
		{irr::KEY_PRINT, L"PRINT"},
		{irr::KEY_EXECUT, L"EXECUTE"},
		{irr::KEY_SNAPSHOT, L"PRINT SCREEN"},
		{irr::KEY_INSERT, L"INSERT"},
		{irr::KEY_DELETE, L"DELETE"},
		{irr::KEY_HELP, L"HELP"},
		{irr::KEY_KEY_0, L"0"},
		{irr::KEY_KEY_1, L"1"},
		{irr::KEY_KEY_2, L"2"},
		{irr::KEY_KEY_3, L"3"},
		{irr::KEY_KEY_4, L"4"},
		{irr::KEY_KEY_5, L"5"},
		{irr::KEY_KEY_6, L"6"},
		{irr::KEY_KEY_7, L"7"},
		{irr::KEY_KEY_8, L"8"},
		{irr::KEY_KEY_9, L"9"},
		{irr::KEY_KEY_A, L"A"},
		{irr::KEY_KEY_B, L"B"},
		{irr::KEY_KEY_C, L"C"},
		{irr::KEY_KEY_D, L"D"},
		{irr::KEY_KEY_E, L"E"},
		{irr::KEY_KEY_F, L"F"},
		{irr::KEY_KEY_G, L"G"},
		{irr::KEY_KEY_H, L"H"},
		{irr::KEY_KEY_I, L"I"},
		{irr::KEY_KEY_J, L"J"},
		{irr::KEY_KEY_K, L"K"},
		{irr::KEY_KEY_L, L"L"},
		{irr::KEY_KEY_M, L"M"},
		{irr::KEY_KEY_N, L"N"},
		{irr::KEY_KEY_O, L"O"},
		{irr::KEY_KEY_P, L"P"},
		{irr::KEY_KEY_Q, L"Q"},
		{irr::KEY_KEY_R, L"R"},
		{irr::KEY_KEY_S, L"S"},
		{irr::KEY_KEY_T, L"T"},
		{irr::KEY_KEY_U, L"U"},
		{irr::KEY_KEY_V, L"V"},
		{irr::KEY_KEY_W, L"W"},
		{irr::KEY_KEY_X, L"X"},
		{irr::KEY_KEY_Y, L"Y"},
		{irr::KEY_KEY_Z, L"Z"},
		{irr::KEY_LWIN, L"LEFT WIN"},
		{irr::KEY_RWIN, L"RIGHT WIN"},
		{irr::KEY_APPS, L"APPS"},
		{irr::KEY_SLEEP, L"SLEEP"},
		{irr::KEY_NUMPAD0, L"NUMPAD 0"},
		{irr::KEY_NUMPAD1, L"NUMPAD 1"},
		{irr::KEY_NUMPAD2, L"NUMPAD 2"},
		{irr::KEY_NUMPAD3, L"NUMPAD 3"},
		{irr::KEY_NUMPAD4, L"NUMPAD 4"},
		{irr::KEY_NUMPAD5, L"NUMPAD 5"},
		{irr::KEY_NUMPAD6, L"NUMPAD 6"},
		{irr::KEY_NUMPAD7, L"NUMPAD 7"},
		{irr::KEY_NUMPAD8, L"NUMPAD 8"},
		{irr::KEY_NUMPAD9, L"NUMPAD 9"},
		{irr::KEY_MULTIPLY, L"MULTIPLY"},
		{irr::KEY_ADD, L"ADD"},
		{irr::KEY_SEPARATOR, L"SEPARATOR"},
		{irr::KEY_SUBTRACT, L"SUBTRACT"},
		{irr::KEY_DECIMAL, L"DECIMAL"},
		{irr::KEY_DIVIDE, L"DIVIDE"},
		{irr::KEY_F1, L"F1"},
		{irr::KEY_F2, L"F2"},
		{irr::KEY_F3, L"F3"},
		{irr::KEY_F4, L"F4"},
		{irr::KEY_F5, L"F5"},
		{irr::KEY_F6, L"F6"},
		{irr::KEY_F7, L"F7"},
		{irr::KEY_F8, L"F8"},
		{irr::KEY_F9, L"F9"},
		{irr::KEY_F10, L"F10"},
		{irr::KEY_F11, L"F11"},
		{irr::KEY_F12, L"F12"},
		{irr::KEY_F13, L"F13"},
		{irr::KEY_F14, L"F14"},
		{irr::KEY_F15, L"F15"},
		{irr::KEY_F16, L"F16"},
		{irr::KEY_F17, L"F17"},
		{irr::KEY_F18, L"F18"},
		{irr::KEY_F19, L"F19"},
		{irr::KEY_F20, L"F20"},
		{irr::KEY_F21, L"F21"},
		{irr::KEY_F22, L"F22"},
		{irr::KEY_F23, L"F23"},
		{irr::KEY_F24, L"F24"},
		{irr::KEY_NUMLOCK, L"NUM LOCK"},
		{irr::KEY_SCROLL, L"SCROLL LOCK"},
		{irr::KEY_LSHIFT, L"LEFT SHIFT"},
		{irr::KEY_RSHIFT, L"RIGHT SHIFT"},
		{irr::KEY_LCONTROL, L"LEFT CONTROL"},
		{irr::KEY_RCONTROL, L"RIGHT CONTROL"},
		{irr::KEY_LMENU, L"LEFT MENU"},
		{irr::KEY_RMENU, L"RIGHT MENU"},
		{irr::KEY_OEM_1, L"OEM 1"},
		{irr::KEY_PLUS, L"PLUS"},
		{irr::KEY_COMMA, L"COMMA"},
		{irr::KEY_MINUS, L"MINUS"},
		{irr::KEY_PERIOD, L"PERIOD"},
		{irr::KEY_OEM_2, L"OEM 2"},
		{irr::KEY_OEM_3, L"OEM 3"},
		{irr::KEY_OEM_4, L"OEM 4"},
		{irr::KEY_OEM_5, L"OEM 5"},
		{irr::KEY_OEM_6, L"OEM 6"},
		{irr::KEY_OEM_7, L"OEM 7"},
		{irr::KEY_OEM_8, L"OEM 8"},
		{irr::KEY_OEM_AX, L"OEM AX"},
		{irr::KEY_OEM_102, L"OEM 102"},
		{irr::KEY_ATTN, L"ATTN"},
		{irr::KEY_CRSEL, L"CRSEL"},
		{irr::KEY_EXSEL, L"EXSEL"},
		{irr::KEY_EREOF, L"EREASE EOF"},
		{irr::KEY_PLAY, L"PLAY"},
		{irr::KEY_ZOOM, L"ZOOM"},
		{irr::KEY_PA1, L"PA1"},
		{irr::KEY_OEM_CLEAR, L"CLEAR"}})
{}

const wchar_t *bomb::IrrKeyToStr::operator[](irr::EKEY_CODE keyCode)
{
	if (_keys.find(keyCode) != _keys.end())
		return _keys[keyCode];
	return L"UNDEFINED";

}